server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLOTHES-DATABASE
          uri: lb://CLOTHES-DATABASE
          predicates:
            - Path=/product/save
            - Path=/shop/all
        - id: USERS-DATABASE
          uri: lb://USERS-DATABASE
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost